# This is a basic workflow to help you get started with Actions

name: Publish stories if changed

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths: ["stories/**", "src/components/**"]
  pull_request:
    branches: [ "master" ]
    paths: ["stories/**", "src/components/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.BDOUGIE_TOKEN }}
        BRANCH: master
        FOLDER: storybook-static
        BUILD_SCRIPT: npm ci && npm run build-storybook
